### ISSUE TITLE
Allow client Faraday adapter to be configured via the 'elastic.yml' file

### ISSUE THREAD

**Issue by iobaixas** [platanus/elastic-rails#5]
Currently only the `host` and `port` are configurable. We should add support for more options, like the Faraday `adapter` (all available options can be seen here: https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/client.rb).

I propose adding the `adapter` option to the `Configuration` class.

**Comment by afromankenobi** [comment]
Hi! i'm working on this and some test are failing, any idea why?
i'm using ruby 2.2, following your travis spec

```
Failures:

  1) Elastic::Core::Connector when index already exists and mapping cant be synchronized migrate regenerates index with new map and moves records to new index
     Failure/Error: api.delete_by_query(index: _index, body: { query: { term: { _mark_for_deletion: true } } })

     Elasticsearch::Transport::Transport::Errors::BadRequest:
       [400] No handler found for uri [/elastic_gem_specs_idx_name%3A1508954385/_query] and method [DELETE]
     # /Users/jorgevargas/.rvm/gems/ruby-2.2.6/gems/elasticsearch-transport-1.1.3/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
     # /Users/jorgevargas/.rvm/gems/ruby-2.2.6/gems/elasticsearch-transport-1.1.3/lib/elasticsearch/transport/transport/base.rb:312:in `perform_request'
     # /Users/jorgevargas/.rvm/gems/ruby-2.2.6/gems/elasticsearch-transport-1.1.3/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
     # /Users/jorgevargas/.rvm/gems/ruby-2.2.6/gems/elasticsearch-transport-1.1.3/lib/elasticsearch/transport/client.rb:128:in `perform_request'
     # /Users/jorgevargas/.rvm/gems/ruby-2.2.6/gems/elasticsearch-api-1.1.3/lib/elasticsearch/api/actions/delete_by_query.rb:71:in `delete_by_query'
     # ./lib/elastic/core/connector.rb:216:in `delete_marked_for_deletion'
     # ./lib/elastic/core/connector.rb:128:in `rollover'
     # ./lib/elastic/core/connector.rb:45:in `migrate'
     # ./spec/lib/core/connector_spec.rb:148:in `block (5 levels) in <top (required)>'
     # ./spec/lib/core/connector_spec.rb:148:in `block (4 levels) in <top (required)>'
     # ./spec/support/elasticsearch.rb:22:in `block (2 levels) in <top (required)>'
```

**Comment by blackjid** [comment]
Hi!, thanks for looking into this...

Are running the tests against elasticsearch 2.4 or higher?? that might be the problem, try with elasticsarch 1.7.

Also be sure to run the tests with `bundle exec rspec spec` to be confident you are using the correct version of the `elasticsearch` gem. That gem is a dependency and the version of the gem has direct relation with the elasticsearch version supported.

**Comment by afromankenobi** [comment]
Thanks @blackjid, installing elasticsearch 1.4 solves the problem.

**Comment by blackjid** [comment]
👍  great!, that's the next step, to upgrade our elasticsearch support to the newer versions...

**Comment by afromankenobi** [comment]
I'll collaborate :)
